// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package platform

import (
	"demo/api/platform"
	"demo/internal/service"
)

type ControllerV1 struct {
	platformService service.PlatformService
}

func NewV1(platformService service.PlatformService) platform.IPlatformV1 {
	return &ControllerV1{
		platformService: platformService,
	}
}
