// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package platform

import (
	"demo/api/platform"
	platformL "demo/internal/logic/platform"
)

type ControllerV1 struct {
	platform platformL.Platform
}

func NewV1() platform.IPlatformV1 {
	return &ControllerV1{}
}
