// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userPlatform

import (
	"demo/api/userPlatform"
	userPlatformL "demo/internal/logic/user-platform"
)

type ControllerV1 struct {
	userPlatform userPlatformL.UserPlatform
}

func NewV1() userPlatform.IUserPlatformV1 {
	return &ControllerV1{
		userPlatform: userPlatformL.UserPlatform{},
	}
}
