// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userPlatform

import (
	"demo/api/userPlatform"
	"demo/internal/service"
)

type ControllerV1 struct {
	userPlatformService service.UserPlatformService
}

func NewV1(userPlatformService service.UserPlatformService) userPlatform.IUserPlatformV1 {
	return &ControllerV1{
		userPlatformService: userPlatformService,
	}
}
