// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package user

import (
	"github.com/quannv/strongbody-api/api/user"
	"github.com/quannv/strongbody-api/internal/service"
)

type ControllerV1 struct {
	userService service.UserService
}

func NewV1(userService service.UserService) user.IUserV1 {
	return &ControllerV1{
		userService: userService,
	}
}
