// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userApp

import (
	"demo/api/userApp"
	"demo/internal/service"
)

type ControllerV1 struct {
	userAppService service.UserAppService
}

func NewV1(userAppService service.UserAppService) userApp.IUserAppV1 {
	return &ControllerV1{
		userAppService: userAppService,
	}
}
