// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"demo/api/role"
	roleL "demo/internal/logic/role"
)

type ControllerV1 struct {
	role roleL.Role
}

func NewV1() role.IRoleV1 {
	return &ControllerV1{
		role: roleL.Role{},
	}
}
