// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package role

import (
	"demo/api/role"
	"demo/internal/service"
)

type ControllerV1 struct {
	roleService service.RoleService
}

func NewV1(roleService service.RoleService) role.IRoleV1 {
	return &ControllerV1{
		roleService: roleService,
	}
}
