
# CLI tool, only in development environment.
# https://goframe.org/docs/cli
gfcli:
  gen:
    dao:
      - link: "mysql:root:12345678@tcp(127.0.0.1:3306)/test"
        descriptionTag: true
  database:
    default:
      type: "mysql"
      host: "127.0.0.1"
      port: "3306"
      user: "root"
      pass: "password"
      name: "testdb"
  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app