// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"strongbody-api/api/auth"
	"strongbody-api/internal/service"
)

type ControllerV1 struct {
	authService service.AuthService
}

func NewV1(authService service.AuthService) auth.IAuthV1 {
	return &ControllerV1{
		authService: authService,
	}
}
