// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package auth

import (
	"demo/api/auth"
	authL "demo/internal/logic/auth"
)

type ControllerV1 struct {
	authLogic authL.AuthLogic
}

func NewV1() auth.IAuthV1 {
	return &ControllerV1{
		authLogic: authL.AuthLogic{},
	}
}
