// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package app

import (
	"demo/api/app"
	"demo/internal/service"
)

type ControllerV1 struct {
	appService service.AppService
}

func NewV1(appService service.AppService) app.IAppV1 {
	return &ControllerV1{
		appService: appService,
	}
}
