// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package token

import (
	"demo/api/token"
	tokenL "demo/internal/logic/token"
)

type ControllerV1 struct {
	token tokenL.Token
}

func NewV1() token.ITokenV1 {
	return &ControllerV1{}
}
