// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package token

import (
	"demo/api/token"
	"demo/internal/service"
)

type ControllerV1 struct {
	tokenService service.TokenService
}

func NewV1(tokenService service.TokenService) token.ITokenV1 {
	return &ControllerV1{
		tokenService: tokenService,
	}
}
