[database]
    [[database.default]]
        type = "pgsql"           
        host = "localhost"       
        port = "5432"            
        user = "root"            
        pass = "secret"          
        name = "CORE_USER"       
        charset = "utf8"         
        timezone = "UTC"        
        maxIdle = 10             
        maxOpen = 100            
        maxLifetime = 1800       