// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// platformDao is the data access object for the table Platform.
// You can define custom methods on it to extend its functionality as needed.
type platformDao struct {
	*internal.PlatformDao
}

var (
	// Platform is a globally accessible object for table Platform operations.
	Platform = platformDao{internal.NewPlatformDao()}
)

// Add your custom methods and functionality below.
