// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// tokensDao is the data access object for the table Tokens.
// You can define custom methods on it to extend its functionality as needed.
type tokensDao struct {
	*internal.TokensDao
}

var (
	// Tokens is a globally accessible object for table Tokens operations.
	Tokens = tokensDao{internal.NewTokensDao()}
)

// Add your custom methods and functionality below.
