// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// userRoleDao is the data access object for the table UserRole.
// You can define custom methods on it to extend its functionality as needed.
type userRoleDao struct {
	*internal.UserRoleDao
}

var (
	// UserRole is a globally accessible object for table UserRole operations.
	UserRole = userRoleDao{internal.NewUserRoleDao()}
)

// Add your custom methods and functionality below.
