// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"demo/internal/dao/internal"
)

// userPlatformDao is the data access object for the table UserPlatform.
// You can define custom methods on it to extend its functionality as needed.
type userPlatformDao struct {
	*internal.UserPlatformDao
}

var (
	// UserPlatform is a globally accessible object for table UserPlatform operations.
	UserPlatform = userPlatformDao{internal.NewUserPlatformDao()}
)

// Add your custom methods and functionality below.
