// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userRole

import (
	"demo/api/userRole"
	"demo/internal/service"
)

type ControllerV1 struct {
	userRoleService service.UserRoleService
}

func NewV1(userRoleService service.UserRoleService) userRole.IUserRoleV1 {
	return &ControllerV1{
		userRoleService: userRoleService,
	}
}
