// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package userRole

import (
	"demo/api/userRole"
	userRoleL "demo/internal/logic/user-role"
)

type ControllerV1 struct {
	userRole userRoleL.UserRole
}

func NewV1() userRole.IUserRoleV1 {
	return &ControllerV1{
		userRole: userRoleL.UserRole{},
	}
}
